## Importing all the necessary packages ##

In [50]:
# This is classification and regression problem where we have to predict the quality of wine(red & white) based on a set of values for features

import pandas as pd# data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra

## Reading the white-wine data ##

In [51]:
# Reading the white-wine csv file

df_white_wine= pd.read_csv("/Users/revasmac/Desktop/Data245_ML/winequality-white.csv")
df_white_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

## Data Preprocessing for white-wine ##

In [55]:
# Checking for NULL values

print(df_white_wine.isnull().values.any())

False

In [41]:
# summary
df_white_wine.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [42]:
# Checking for categorical values

print(df_white_wine.shape)

df_white_wine.info()

(4898, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [44]:
# Checking for duplicate rows

df_white_wine=df_white_wine.drop_duplicates()
df_white_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [45]:
# Creating a copy of the white-wine dataset so that the original dataset will not change.

df_white_wine_cf = df_white_wine.copy()
df_white_wine_cf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [46]:
# Adding "_" in between all the columns of white-wine dataset

df_white_wine_cf.columns = df_white_wine.columns.str.replace(" ", "_")
df_white_wine_cf

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

## Converting into binary classification ##

In [62]:
# For binary classification of the target variable we are adding one new column named "quality_rank" and making it "0" for quality between (1-6) and "1" for quality (7&8)

df_white_wine_cf['quality_rank'] = [1 if x >= 7 else 0 for x in df_white_wine_cf['quality']]
df_white_wine_cf

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,quality_rank
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,0
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,0
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,0
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,0
6,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,0
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,0
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,0
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,0

In [66]:
# Separating the feature variables and target variable

X_white = df_white_wine_cf.drop(['quality','quality_rank'], axis = 1)
y_white = df_white_wine_cf['quality_rank']

In [67]:
# See proportion of wines based on quality_rank for making sure that data is not imbalanced.

df_white_wine_cf['quality_rank'].value_counts()

0    3136
1     825
Name: quality_rank, dtype: int64

#### Based on above result we can see that it's fair enough to fit the data into model!!!####

## Preparing data for modeling ##

#### Standardizing feature variables in order to equalize the range of the data.####

In [68]:
# Normalize feature variables

from sklearn.preprocessing import StandardScaler

X_features_white = X_white 
X_white = StandardScaler().fit_transform(X_white)

## Split data ##

In [134]:
# Splitting the data into 70% training and 30% test 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_white, y_white, test_size=0.3, random_state=0)

## Classification model for white-wine ##

In [146]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
white_clf = svm.SVC(kernel='poly') # Polynomial Kernel

#Train the model using the training sets
white_clf.fit(X_train, y_train)

#Predict the response for test dataset
white_y_pred = white_clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, white_y_pred))

Accuracy: 0.8200168208578638

In [150]:
#check the areaUnderROC value
from sklearn.metrics import roc_auc_score
print("areaUnderROC:",metrics.roc_auc_score(y_test, white_y_pred))

areaUnderROC: 0.7642401621729787

## Regression model for white-wine ##

In [165]:
#Import svm model
from sklearn import svm

#Create a svm Regression
white_rng = svm.SVR(kernel='poly') # polynomial Kernel

#Train the model using the training sets
white_rng.fit(X_train, y_train)

#Predict the response for test dataset
white_y_pred = white_rng.predict(X_test)
white_y_pred

array([ 5.08668154e-02,  4.16145629e-02,  7.48933663e-02, -3.52391095e+00,
        1.60218626e-01,  1.04271982e-01,  6.98540104e-02, -4.27862485e-02,
        1.78216544e-02,  3.21556363e-01,  1.77054361e-01,  8.31296163e-01,
       -1.02876124e-03,  5.08524005e-02,  4.13830977e-01,  5.20655145e-01,
       -8.33092896e-04,  7.92472097e-03, -1.73536445e+00,  1.42467477e-01,
        6.30760656e-02,  1.37864926e-01,  5.92991741e-01, -1.89474464e-01,
        2.79077561e-01,  1.06150839e+00,  8.79664078e-02,  2.69993246e-01,
        1.16523393e-01, -9.92217801e-02, -4.15761581e-02,  1.03789452e-01,
       -3.89494504e-03,  1.03770023e-01,  2.27881352e+00,  1.55920687e-01,
        1.09603245e-01, -2.72541205e+00,  6.63376714e-02, -5.39361700e-01,
        7.84186898e-02, -1.45184886e-02,  1.69474586e-01,  7.04397367e-02,
        2.37937828e-01,  6.70027863e-02,  4.25748316e-02,  8.76208359e-02,
        1.08188220e-01,  8.64229088e-02,  2.05051811e-01,  5.68677261e-02,
       -4.37494766e+00,  3.72423910e-02,  5.96581612e-02,  2.00172316e-01,
        8.73808504e-02,  3.59955272e-01,  7.46371243e-02,  1.51989092e+00,
       -1.33156445e-01,  9.92379774e-02,  2.44688139e-01,  2.77482423e-03,
        1.53233075e-01,  7.32783955e-02,  7.30278941e-01,  2.55733423e-01,
       -1.02314133e-01, -1.46522071e-01,  5.01990580e-02,  2.73181343e-02,
       -2.37248128e-03,  1.30350417e-01,  1.97226771e-01,  1.50302446e-01,
        8.11920713e-02,  7.34577836e-02,  1.33886221e-01, -7.57779182e-01,
        1.66349453e-02,  9.53146621e-02,  1.63691064e-01,  4.58113199e-01,
        1.24164529e-01, -2.99295960e-01,  8.02498017e-02,  1.73629505e-01,
        9.25595454e-02,  9.12641034e-02,  1.61133118e-01, -1.33206604e-01,
        4.86064659e-02,  3.04934481e-02,  4.97065238e-02,  3.03885340e-02,
        1.56484655e-01, -3.88326113e-02, -1.53825845e-02,  1.87834594e-01,
        2.43081260e-01, -5.52663164e-02,  1.79316327e-01,  1.51440075e-01,
       -4.64837444e-01,  1.27050894e-01, -4.55214487e-02,  3.47935751e-02,
        8.57405696e-02,  1.50205273e-01, -1.44314436e-01,  8.01075121e-02,
        4.89771794e-02,  6.47174496e-02,  4.87731577e-02, -1.03088890e-01,
        1.83055050e-01,  1.25949172e-01,  1.99110336e-01,  9.55378540e-02,
       -4.11784064e-03,  1.20969901e-01,  1.83300334e-01,  8.08392873e-02,
       -3.10956259e-02,  1.20796543e-01,  1.43646875e-01,  2.38932524e-01,
        7.63463788e-02,  9.21826391e-02,  2.07783754e-01,  4.89970507e-02,
        1.23195645e-01,  3.45872745e-01,  1.34941674e-01,  6.05875974e-01,
        7.09394827e-02,  2.91577252e-01,  1.35014474e-01,  2.54443950e-01,
        7.71595599e-02,  5.38838134e-02, -1.12454093e+00,  4.54449404e-02,
        9.24601033e-02,  3.39445122e-02,  9.01513416e-02, -4.62534493e-02,
       -3.77136772e-01,  2.47394754e-01,  6.23737356e-02,  3.03121565e-01,
        4.07139755e-02, -1.21466818e-01,  4.63767693e-02,  5.17226921e-02,
        3.46982227e+00, -9.66228018e-02,  2.87976202e-01,  1.57567021e-01,
        1.01512454e-01,  9.28819913e-02, -9.87373654e-01,  8.56125265e-02,
        1.35293186e-01,  9.50050470e-02,  8.07819062e-02,  2.80793675e-01,
        9.65299976e-02, -2.69489252e-03, -5.39411341e-01, -9.20049100e-03,
        5.13653345e-02,  7.12716591e-01,  1.49779704e-02,  1.08163718e-01,
        3.78615564e-02,  8.86274278e-02,  8.22277722e-02, -2.13290719e-01,
       -4.04382329e+00,  7.70879438e-02,  1.01693984e-01,  6.56992359e-02,
        1.68460000e-01, -4.40279768e-01,  1.56883543e-01,  1.37824580e-01,
        1.81072261e-01,  2.61170414e-01,  9.95514882e-02,  9.05452979e-02,
        1.08374766e-01,  7.62551728e-02,  6.56735882e-02,  1.31355153e-01,
        8.29221203e-01,  7.96283575e-02,  6.68606118e-02,  9.99068719e-02,
        9.38347443e-02,  3.63861098e-01,  2.24695220e-01,  1.27756835e-01,
        2.23629316e-02,  3.98509025e-02,  9.09482485e-02,  7.49455580e-02,
        5.38330587e-02,  7.39049621e-02,  9.82498838e-02,  1.51684236e-01,
        1.79951834e-01,  7.96394463e-02,  7.67019648e-02,  4.63222957e-02,
       -1.49134801e-01, -4.69838998e-01,  1.66835044e-01,  9.43084336e-02,
       -3.10055132e-01,  1.27842023e-01,  8.77301512e-02, -1.55053663e-02,
        9.08430536e-01,  7.02883245e-01,  5.42862098e-02, -1.60415724e-01,
        1.68540973e-01,  6.09814407e-02,  9.87708762e-02,  5.06046992e-01,
        6.79820200e-02,  1.50213914e+00,  8.30407398e-02,  1.89949787e-02,
        3.85182003e-02, -2.90397917e-02,  6.56635655e-02,  8.50121455e-02,
        5.76472948e-02,  1.60531257e-01, -1.36617053e-01, -3.67578569e-01,
        2.15390507e-01,  3.09482023e-02,  1.98295970e-01,  6.57133087e-02,
       -1.56655867e-03,  1.11450741e-01,  7.98166273e-02,  3.56336350e-03,
        8.51931425e-02,  5.71913954e-02,  7.82457835e-02,  6.06914077e-02,
        1.02205522e-01,  7.61530564e-02,  1.91442255e-01,  1.29509607e-01,
        1.13472347e-01,  1.21609439e-01,  5.09270726e-02,  3.31777413e-02,
        7.05557106e-02,  1.53084015e-01,  1.28670796e+00, -5.55448969e-01,
       -1.25214984e-01, -2.00774241e-01, -5.87383486e-02,  2.28070874e-01,
        8.92640444e-02,  7.84426618e-01,  1.19783978e-01,  3.51823968e-02,
        7.76726692e-02,  8.19118826e-02, -3.69149376e-01,  7.65486021e-02,
        7.40833162e-02,  7.10396297e-02,  4.93155118e-01,  2.79707337e-01,
        8.75236012e-02,  5.88674304e-02,  9.10532758e-02,  1.19094181e-01,
        1.45955737e-01,  5.75494969e-02,  8.58527381e-02,  2.77058864e-02,
        1.44819687e-01,  5.36572851e-02,  7.04718074e-02,  1.08746265e-01,
        3.50671076e-01,  2.44050552e-02,  1.08073839e-01,  2.88660547e-02,
        9.58948225e-02,  2.85214207e-01,  9.53672784e-02,  4.10453821e-03,
       -1.54523980e+00,  8.60671664e-02, -4.97319126e-03, -1.73454789e-01,
       -3.74438755e-01,  5.92233231e-01, -1.49751421e-01, -8.98010010e-03,
       -2.65809588e-01,  1.10282461e-01,  1.03312913e-01,  7.10901836e-02,
        5.64043106e-02, -1.71026385e-02, -2.81626872e-02, -1.21881625e-01,
       -1.32744332e-02, -2.53497606e-02,  1.91854727e-01,  5.45243499e-02,
        1.04092792e-01,  2.76822814e-04,  1.07730991e-01,  1.92669241e-01,
        7.16160307e-03,  6.10340374e-02,  1.09220945e-01,  3.41268779e-02,
       -4.48403417e-03, -3.94283321e-03,  8.91303154e-02,  5.89274566e-02,
       -1.35045339e-02, -1.29036831e-01,  1.26394905e-01,  7.83881827e-02,
        1.27059688e-03,  9.70868958e-02,  6.34850191e-02,  9.19081690e-02,
       -1.97799374e-01, -3.91184789e-01, -8.97075543e-02,  6.44751087e-02,
        1.45641870e-01, -3.11623883e-03,  6.49414716e-02,  8.04311174e-02,
        1.05427565e-01,  1.46359645e-01, -5.68008742e-02,  6.58168542e-02,
        6.87368353e-02, -1.45163131e-01, -5.12132600e-01,  8.65519004e-02,
        5.71059065e-02,  2.49032025e-01,  9.05306139e-02, -4.56251484e-02,
        1.73376228e-01,  9.86135190e-02,  7.48913946e-02, -1.82162130e-01,
        1.40766936e-01,  7.46190237e-02,  7.71954936e-02,  8.53957073e-02,
        2.45708134e-02, -7.09982394e-02,  3.69171430e-01, -1.98722766e-03,
        5.32968413e-02,  1.05913912e-01,  1.53518719e-01,  2.08364294e-01,
       -2.87304699e-01,  7.37739574e-02,  1.12982795e-01,  9.29758218e-02,
       -4.60053832e-02,  2.16731140e-02, -4.98242545e-01, -5.08687408e-01,
       -1.96520325e-02,  2.98949305e-02, -2.35224894e-02,  9.00743046e-02,
       -1.12900094e-01,  8.20507095e-01,  9.76175330e-02,  4.45259208e-02,
        9.18075953e-02,  8.54916429e-02, -1.72860694e-02,  4.11714448e-02,
       -3.26198967e-01,  1.71425501e-01,  2.88200650e-02, -1.79040404e-02,
        1.75384772e-01,  3.14567367e-01,  5.76291272e-02,  9.54039039e-02])

In [151]:
#Check the r2-score value.
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print(" The r-square_value",metrics.r2_score(y_test, white_y_pred))

 The r-square_value -1.1900635341210797

In [152]:
print(" The rmse_score:",metrics.mean_squared_error(y_test, white_y_pred, squared=False))

 The rmse_score: 0.5967538194983792

## Reading the red-wine data ##

In [117]:
# Reading the red-wine csv file

df_red_wine= pd.read_csv("/Users/revasmac/Desktop/Data245_ML/winequality-red.csv")
df_red_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

## Data Preprocessing for red-wine ##

In [85]:
# Checking for NULL values

print(df_red_wine.isnull().values.any())

False

In [86]:
# summary
df_red_wine.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [87]:
# Checking for categorical values

print(df_red_wine.shape)

df_red_wine.info()

(1599, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [88]:
# Checking for duplicate rows

df_red_wine=df_red_wine.drop_duplicates()
df_red_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [89]:
# Creating a copy of the red wine dataset so that the original dataset will not change.

df_red_wine_cf = df_red_wine.copy()
df_red_wine_cf

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [90]:
# Adding "_" in between all the columns of red wine dataset

df_red_wine_cf.columns = df_red_wine.columns.str.replace(" ", "_")
df_red_wine_cf

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [91]:
# For binary classification of the target variable we are adding one new column named "quality_rank" and making it "0" for quality between (1-6) and "1" for quality (7&8)

df_red_wine_cf['quality_rank'] = [1 if x >= 7 else 0 for x in df_red_wine_cf['quality']]
df_red_wine_cf

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,quality_rank
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,0
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,0
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,0
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,0

In [92]:
# Separating the feature variables and target variable

X_red = df_red_wine_cf.drop(['quality','quality_rank'], axis = 1)
y_red = df_red_wine_cf['quality_rank']

In [93]:
# See proportion of wines based on quality_rank for making sure that data is not imbalanced.

df_red_wine_cf['quality_rank'].value_counts()

0    1175
1     184
Name: quality_rank, dtype: int64

#### Based on above result we can see that it's fair enough to fit the data into model!!!####

## Preparing data for modeling ##

#### Standardizing feature variables in order to equalize the range of the data.####

In [94]:
# Normalize feature variables

from sklearn.preprocessing import StandardScaler

X_features_red = X_red 
X_red = StandardScaler().fit_transform(X_red)

## Split data ##

In [157]:
# Splitting the data into training and test dataset.

from sklearn.model_selection import train_test_split
X_true, X_test, y_true, y_test = train_test_split(X_red, y_red, test_size=.30, random_state=0)

## Classification Model for red-wine ##

In [158]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
red_clf = svm.SVC(kernel='poly') # Polynomial Kernel

#Train the model using the training sets
red_clf.fit(X_true, y_true)

#Predict the response for test dataset
red_y_pred = red_clf.predict(X_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, red_y_pred))

Accuracy: 0.8186274509803921

In [159]:
#check the areaUnderROC value
from sklearn.metrics import roc_auc_score
print("areaUnderROC:",metrics.roc_auc_score(y_test, red_y_pred))

areaUnderROC: 0.5424430641821946

## Regression model for red-wine ##

In [164]:
#Import svm model
from sklearn import svm

#Create a svm Regression
red_rng = svm.SVR(kernel='poly') # polynomial Kernel

#Train the model using the training sets
red_rng.fit(X_true, y_true)

#Predict the response for test dataset
red_y_pred = red_rng.predict(X_test)
red_y_pred

array([ 2.69378672e-01,  9.52444993e-02,  6.20838396e-02, -6.63530363e-01,
        9.50933331e-02,  3.85705145e-02,  9.60101868e-02,  4.70620672e-02,
       -1.09826153e-02,  6.56012961e-02,  4.38202495e-02, -1.11641119e-01,
       -2.08607948e-02,  1.84973551e-02,  6.24126877e-01,  4.28618662e-02,
        2.52382245e-01, -5.15243311e-03, -1.04804926e-01,  9.84000287e-02,
       -9.05653783e-02, -9.84880558e-02,  2.73906113e-02, -1.68202938e-01,
        3.12580234e-02,  3.97906177e+00,  3.06344142e-01,  1.45092622e-01,
       -1.59688488e-02, -1.50592374e-01,  2.43924299e-02, -1.63995380e-02,
       -4.04474344e-02,  6.00609495e-02,  3.49707303e-01,  3.11573128e-03,
       -6.69180257e-03,  1.83616729e+00,  6.15808827e-02, -1.32817046e+00,
        3.94051553e-02,  5.48654178e-02,  3.14573653e-01,  1.88272789e-01,
        3.12106718e-01,  3.49399864e-02, -1.85201954e-01,  1.26004340e-01,
        4.57471516e-02,  9.96949383e-02,  4.14993140e-01,  5.72169564e-02,
        2.16783652e+00,  6.38866649e-02,  1.43772440e-01,  9.45791285e-01,
        4.26406327e-02, -3.34127045e-01,  6.25400030e-02,  1.17305965e+00,
       -8.44592912e-03, -6.32501688e-03,  9.14355450e-01, -1.80955467e-02,
        2.20403868e-01,  2.06568372e-02,  1.36255978e-01,  4.70284444e-02,
       -5.81978701e-02,  2.26080440e-01,  2.73174391e-02,  8.91538044e-02,
        6.55919337e-02, -7.61197738e-03,  2.77062041e-01,  1.56587227e-02,
        8.00827989e-02, -1.44693978e-01,  9.91379442e-02, -1.85833703e-03,
        3.69894450e-02,  6.53744884e-02,  2.51487686e-01,  2.74622057e-01,
        7.08699045e-02,  3.25862702e-01,  5.34334753e-02, -6.88181967e-02,
        5.95213649e-02,  1.51647415e-01,  3.98328810e-01,  9.63585270e-01,
        6.64368566e-02,  6.16067056e-02, -1.17015381e-02, -1.39079311e-02,
        3.91435877e-01,  3.54039123e-02,  3.28186831e-02, -3.86797833e-02,
        1.07686124e-01,  2.59782139e-02,  2.26311375e-01,  5.40811739e-02,
       -1.09412465e-01,  1.06369508e-01,  5.22675097e-02, -9.96107811e-03,
        5.65671611e-01, -2.50115920e-02,  1.34356374e-01,  5.08128722e-02,
        5.55851768e-02,  1.81715449e-01,  1.93513209e-01,  2.38180472e-01,
        6.49953475e-02,  2.15308077e-01, -1.68732833e-01,  9.23050072e-02,
       -9.25011372e-02, -7.95539129e-02,  6.24431503e-02,  7.38517894e-02,
        2.10898526e-01,  2.14312327e-01,  7.91790055e-02,  1.40811994e-01,
       -6.48031666e-02,  2.36915542e-03,  1.22171027e-01,  3.22400138e-01,
        2.28239034e-01, -1.16334502e+00,  2.66882016e-02, -4.95358682e-02,
        3.32826528e-01,  3.06075497e-01,  2.32703727e-01, -2.83092470e-02,
        8.95112427e-02, -5.74682414e-02,  3.75434915e-01,  6.85643124e-02,
       -2.90646782e-03,  9.39773154e-02,  1.44356632e-01, -4.59075759e-02,
       -1.30680197e-02,  2.97428219e-01,  5.13946636e-02, -2.44029614e-01,
        5.36789958e-02,  1.79239689e+00, -5.66623449e-02,  4.64321797e-03,
        7.17087872e-01,  2.65067950e-01,  3.40144050e-01,  1.63348771e-01,
        9.96044454e-04,  3.49110354e-02, -1.58418072e-01,  6.68465945e-02,
        4.64380095e-02, -1.09934923e-02,  5.93775802e-03,  3.63060194e-02,
        5.16214802e-02,  2.43476797e-01,  4.34373781e-02,  2.16221587e-02,
        1.78469162e-02,  5.82727789e-01,  7.08705723e-02,  1.32699012e-02,
        9.36844439e-02,  6.42852345e-02, -8.04942763e-02, -6.66438683e-02,
       -8.19670558e-01,  1.19986485e-01,  4.14847935e-02,  5.17403115e-02,
        9.20331641e-04, -1.21426968e+00,  3.52326856e-02,  5.73680352e-02,
        3.28871712e-01,  3.33866704e-01,  7.72752754e-02,  6.02504869e-02,
        6.25998969e-02, -1.44611750e-01,  5.75138360e-02,  3.44350472e-01,
        2.27008915e-01,  5.68408467e-02,  1.27220475e-01,  7.85990088e-02,
        5.47997391e-02, -4.89916929e-02,  8.69590237e-02, -4.46063663e-02,
       -1.00253683e-01,  8.67474882e-02, -3.47691531e-02,  1.11855770e-02,
        9.04641124e-02,  9.78769003e-02,  6.34053601e-02,  5.89790373e-01,
        6.45674334e-02,  4.41369509e-02,  6.63760204e-02,  3.34437039e-02,
        3.53320934e-02, -1.17082601e-01,  5.82007556e-01,  5.44055172e-02,
        7.13184940e-02,  1.20777875e-01,  3.93364939e-02,  2.85958303e-02,
        3.39538267e-01, -4.53447592e-02,  4.15052645e-03,  1.37330057e-01,
        1.89011482e-03,  3.35672636e-02,  2.75549286e-02,  5.00242747e-01,
        5.17356916e-02,  5.76785338e-01,  1.53366954e-01, -7.61178567e-02,
        5.77288176e-02,  7.69140651e-02,  5.17444635e-02,  4.94731663e-02,
        6.02678576e-02,  1.28353800e-01,  1.18105732e-01,  1.15695535e-01,
        2.69678701e-01,  6.26212755e-02,  2.52063129e-01, -4.93157085e-03,
       -9.55677260e-03,  1.75546316e-01,  6.48771485e-02, -2.01093485e-02,
        1.62382590e-01, -9.48893038e-03,  6.76413485e-02, -2.60438636e-02,
        6.00619503e-02,  3.13236098e-01, -2.37180047e-02, -4.20653239e-02,
       -2.06749083e-02,  7.21176677e-02,  7.78581081e-01,  1.30583139e-01,
        7.51423606e-02,  8.33284286e-02,  1.16598047e+00,  3.97620497e-01,
       -1.94476118e-02, -2.65932651e-01, -1.80855464e-02,  1.26470515e-02,
        2.84099787e-02,  4.91758215e-01,  2.20383611e-01,  2.02303054e-01,
        5.21455326e-02,  7.00179236e-02, -2.27176639e-01,  6.62765106e-02,
        2.69700680e-01,  3.85039510e-02,  2.72953803e-01,  8.50052730e-02,
        4.63303604e-02,  6.34591353e-02,  5.72332351e-02,  1.00486452e-01,
        2.57820346e-02,  4.53390444e-02,  5.20310569e-02,  1.97447126e-01,
        1.79368761e-01,  1.46150426e-01,  1.38033211e-01,  7.48636909e-02,
        1.51056470e-01,  1.14767100e-01,  3.00120588e-01,  1.06391529e-03,
        2.75363642e-01,  1.81849859e-01,  1.26770647e-02,  9.31104832e-02,
        3.76008650e-01,  2.01772176e-02,  1.89007117e-02,  5.09865857e-01,
        1.79071648e-02,  2.19326466e-01,  3.20570902e-01,  1.29133132e-01,
       -1.42293622e-01,  5.81044513e-02,  4.91661319e-02, -3.73335031e-03,
        3.30467877e-02,  5.41936149e-02, -1.03848697e-02,  4.45136343e-01,
        1.01934813e-01,  1.02089384e-01,  8.26745289e-02,  2.11472612e-02,
        8.85789031e-03,  7.04027259e-02,  2.84632467e-01,  1.39484385e-01,
        7.24894684e-02,  7.43829031e-02,  1.71269376e-01, -2.06627358e-02,
        6.95871236e-02, -4.05759637e-02,  6.74314124e-02,  1.09971138e-01,
       -1.33123474e-02,  2.51011674e-01,  4.24260022e-01,  2.81816058e-02,
        1.33301478e-02,  6.87914343e-02,  2.10276583e-02,  3.64814677e-02,
        1.21343761e-01,  6.78889682e-01,  8.88959020e-02,  6.26698138e-02,
       -5.93714655e-03,  1.80023451e-04,  1.02858287e-01,  4.29458567e-03,
        2.85664423e-01,  3.72114127e-02,  3.08730804e-01,  6.04396316e-02,
        1.10745363e-01, -1.87584773e-01, -1.90583674e-01,  6.57399793e-02,
        1.48780724e-02,  1.24596202e-01,  7.12790549e-02, -7.56235560e-02,
       -2.34398240e-01,  7.78711493e-03,  4.08678798e-02,  8.70317317e-02,
       -8.28352726e-03,  7.38729079e-02,  1.22896390e-01,  7.66909080e-03,
        4.73306765e-01,  7.91639544e-02,  2.74627716e-01,  1.78117376e-01,
        8.06608856e-03,  5.84570510e-02, -2.65546811e-03, -2.84508283e-01,
        5.19173618e-02,  1.41719380e-01,  3.40526034e-02,  6.05129007e-02,
       -3.47514523e-02,  5.30021237e-02, -5.37153187e-02, -9.38905691e-01,
       -5.28817129e-04,  1.53924639e-01,  5.08715602e-02,  5.79197151e-02,
       -5.47762182e-02,  1.31613114e+00,  6.30973792e-02, -1.38670327e-02,
        6.04307350e-02, -1.60069671e-02,  1.58935494e-01,  3.49966683e-03,
        1.47035291e-01,  6.09698850e-01,  3.21790449e-02,  1.26319046e-01,
        1.11588871e-01,  4.80876606e-01,  1.43366314e-01,  7.13937753e-02])

In [166]:
#Check the r2-score value.
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print(" The r-square_value",metrics.r2_score(y_test, red_y_pred))

 The r-square_value -0.7069682287834156

In [167]:
print(" The rmse_score:",metrics.mean_squared_error(y_test, red_y_pred, squared=False))

 The rmse_score: 0.47209823642687704